name: Merge master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  clean:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Remove tests
      run: rm -rf tests

    - name: Remove actions
      run: rm -rf .github

